# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    mobile_base_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    spine_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    full_body_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

right_arm_controller:
  ros__parameters:
    joints:
      - right_fr3v2_joint1
      - right_fr3v2_joint2
      - right_fr3v2_joint3
      - right_fr3v2_joint4
      - right_fr3v2_joint5
      - right_fr3v2_joint6
      - right_fr3v2_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
left_arm_controller:
  ros__parameters:
    joints:
      - left_fr3v2_joint1
      - left_fr3v2_joint2
      - left_fr3v2_joint3
      - left_fr3v2_joint4
      - left_fr3v2_joint5
      - left_fr3v2_joint6
      - left_fr3v2_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
mobile_base_controller:
  ros__parameters:
    joints:
      - planar_base_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
spine_controller:
  ros__parameters:
    joints:
      - franka_spine_vertical_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
left_hand_controller:
  ros__parameters:
    joints:
      - left_fr3v2_finger_joint1
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
right_hand_controller:
  ros__parameters:
    joints:
      - right_fr3v2_finger_joint1
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
full_body_controller:
  ros__parameters:
    joints:
      - planar_base_joint
      - franka_spine_vertical_joint
      - left_fr3v2_joint1
      - left_fr3v2_joint2
      - left_fr3v2_joint3
      - left_fr3v2_joint4
      - left_fr3v2_joint5
      - left_fr3v2_joint6
      - left_fr3v2_joint7
      - right_fr3v2_joint1
      - right_fr3v2_joint2
      - right_fr3v2_joint3
      - right_fr3v2_joint4
      - right_fr3v2_joint5
      - right_fr3v2_joint6
      - right_fr3v2_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true