/**:
  controller_manager:
    ros__parameters:
      update_rate: 1000  # Hz

      joint_position_example_controller:
        type: franka_example_controllers/JointPositionExampleController

      joint_velocity_example_controller:
        type: franka_example_controllers/JointVelocityExampleController

      joint_impedance_example_controller:
        type: franka_example_controllers/JointImpedanceExampleController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      mobile_fr3_duo_joint_impedance_example_controller:
        type: franka_example_controllers/MobileFr3DuoJointImpedanceExampleController
      
      gravity_compensation_example_controller:
        type: franka_example_controllers/GravityCompensationExampleController
    
      mobile_cartesian_velocity_controller:
        type: franka_example_controllers/MobileCartesianVelocityExampleController

      swerve_ik_controller:
        type: franka_example_controllers/SwerveIKController

/**:
  joint_position_example_controller:
    ros__parameters:
      robot_type: "fr3"
      gazebo: true

/**:
  joint_velocity_example_controller:
    ros__parameters:
      robot_type: "fr3"
      gazebo: true

/**:    
  joint_impedance_example_controller:
    ros__parameters:
      robot_type: "fr3"
      k_gains:
        - 24.0
        - 24.0
        - 24.0
        - 24.0
        - 10.0
        - 6.0
        - 2.0
      d_gains:
        - 2.0
        - 2.0
        - 2.0
        - 1.0
        - 1.0
        - 1.0
        - 0.5

/**:
  swerve_ik_controller:
    ros__parameters:
      prefix: "tmrv0_2"

/**:
  mobile_cartesian_velocity_controller:
    ros__parameters:
      cartesian_velocity_interface_prefix: swerve_ik_controller/
