#pragma once

// system
#include <limits>
#include <memory>
#include <string>
#include <vector>

#include <Eigen/Eigen>

#include <controller_interface/chainable_controller_interface.hpp>

// auto-generated by generate_parameter_library
// #include "ros2_control_demo_example_12/passthrough_controller_parameters.hpp"

/**
 * SwerveIK is a simple chainable controller that performs IK for TMR. Currently only used for gazebo simulation.
 */
namespace franka_example_controllers
{


class SwerveIKController : public controller_interface::ChainableControllerInterface
{
public:
  controller_interface::CallbackReturn on_init() override;

  controller_interface::InterfaceConfiguration command_interface_configuration() const override;

  controller_interface::InterfaceConfiguration state_interface_configuration() const override;

  controller_interface::CallbackReturn on_configure(
    const rclcpp_lifecycle::State & previous_state) override;

  controller_interface::CallbackReturn on_activate(
    const rclcpp_lifecycle::State & previous_state) override;

  controller_interface::CallbackReturn on_deactivate(
    const rclcpp_lifecycle::State & previous_state) override;

  bool on_set_chained_mode(bool chained_mode) override;

  controller_interface::return_type update_and_write_commands(
    const rclcpp::Time & time, const rclcpp::Duration & period) override;

protected:
  std::vector<hardware_interface::CommandInterface> on_export_reference_interfaces() override;

  controller_interface::return_type update_reference_from_subscribers(
    const rclcpp::Time & time, const rclcpp::Duration & period) override;
  
private:
  Eigen::Vector4d wheel_positions_, steering_angles_, wheel_velocities_;
  const int num_base_joints = 4;
  const double k_mobile_time_max_{8.0};  // Longer period for mobile base
  const double k_mobile_v_max_{0.1};     // Max linear velocity (m/s)
  const double k_mobile_angle_{0.0};     // Move forward/backward
  double elapsed_time_{0.0};
  double wheel_radius_{0.0};

  std::string prefix_;
};

}  // namespace franka_example_controllers

